### ISSUE TITLE
SVGA官方插件於adobe animate安裝皆不成功問題[win10]

### ISSUE THREAD

**Issue by carlnyang** [svga/docs#22]
[更新]安裝ZXP installer（https://aescripts.com/learn/zxp-installer/)
顯示僅相容至animate 2018版，同時網路上也有人分享2020版windows無法使用
（詳情如下圖所示）
![image](https://user-images.githubusercontent.com/76508186/102972544-2c606f00-4536-11eb-9f85-9f7e177878b5.png)

-----------------------以下為起始問題
我剛試裝了SVGA官方的插件到animate軟件中皆不成功
（2021兩版/2020版都不行，重開機與軟體多次也未出現該插件，但系統安裝時是有顯示安裝成功的）
但試裝After Effects的成功，（我的電腦是window 10版本,，使用的是adobe正版授權軟件）
網路上我“目前”也找不到其它解決方案，不曉得是否有人可以熱心解答呢？謝謝

![image](https://user-images.githubusercontent.com/76508186/102962218-52c7df80-4521-11eb-8792-e842d0bd1814.png)
![image](https://user-images.githubusercontent.com/76508186/102962270-74c16200-4521-11eb-8fe1-3e2be90fa2f0.png)

以下是AN安裝版本及不成功的畫面：
若安裝成功時擴充功能內會多第三個項目為SVGAConverter才對
![image](https://user-images.githubusercontent.com/76508186/102963885-37f76a00-4525-11eb-8364-a61cf0119cdb.png)
![image](https://user-images.githubusercontent.com/76508186/102963910-4776b300-4525-11eb-8cf1-6a7a4295d82f.png)

**Comment by PonyCui** [comment]
AN 插件挺旧了，只支持到 2018，需要看看怎么升级一下才行。

**Comment by carlnyang** [comment]
> AN插件挺舊了，只支持到2018，需要看看怎麼升級一下才行。

是的~唯一的QQ群不給加
然後官網也沒有客服
寫信至cuis@vip.qq.com（不知是否為SVAG官方代表郵箱？）
及ZXP版的問題回報https://aescripts.com/helpdesk/index/view/ticket/5dd5656a247710fe39be7cdf8d9ccd99/
二天了都沒人回覆
哈~看來只好停損了！謝謝各位先進

**Comment by PINOOOO** [comment]
目前重新将AN插件的版本限制放开（2019 CC能正常使用），但2020版本以及2021版本中有部分兼容性需要修复。目前想要正常使用建议替换为2019CC版本。
[SVGAConverter_FL.zip](https://github.com/svga/docs/files/5795428/SVGAConverter_FL.zip)
