### ISSUE TITLE
SVGA Unity官方插件 單一軸縮放+旋轉 顯示問題

### ISSUE THREAD

**Issue by FunsTW** [svga/docs#31]
測試圖
![SVAGUnityProblem](https://i.imgur.com/GS5JToW.jpg)

從 SVGA 讀取到的 Transform 矩陣數值推測
有可能是 旋轉矩陣 縮放矩陣 相乘順序問題？

**Comment by PonyCui** [comment]
建议你联系原作者修正问题 https://github.com/svga/SVGAPlayer-Unity/commits?author=lloyar
