### ISSUE TITLE
Android列表播放问题

### ISSUE THREAD

**Issue by ansen666** [svga/docs#4]
我在ViewPager中item里面使用SVGA，发现在滑动过程中有些Item不能正常显示SVAG动画。适配器代码如下,会不会跟复用有关系？请求帮忙看下，谢谢：

`public class ListAdapter extends RecyclerView.Adapter<ListAdapter.ViewHolder>{
    private Context context;

    public ListAdapter(Context context){
        this.context=context;
    }

    @NonNull
    @Override
    public ListAdapter.ViewHolder onCreateViewHolder(@NonNull ViewGroup parent, int viewType) {
        View view = LayoutInflater.from(parent.getContext()).inflate(R.layout.item_list, parent, false);
        return new ViewHolder(view);
    }

    @Override
    public void onBindViewHolder(@NonNull final ListAdapter.ViewHolder holder, int position) {
        SVGAParser parser = new SVGAParser(context);
        parser.decodeFromAssets("angel.svga", new SVGAParser.ParseCompletion() {
            @Override
            public void onComplete(@NotNull SVGAVideoEntity videoItem) {
                holder.svga.setVideoItem(videoItem);
                holder.svga.startAnimation();
            }
            @Override
            public void onError() {

            }
        });
    }

    @Override
    public int getItemCount() {
        return 20;
    }

    public class ViewHolder extends RecyclerView.ViewHolder {
        private SVGAImageView svga;

        public ViewHolder(View view) {
            super(view);

            svga=view.findViewById(R.id.svga);
        }
    }
}`

**Comment by PonyCui** [comment]
复用导致动画暂停

**Comment by ansen666** [comment]
那这个能解决吗？或者我要怎么调用？

**Comment by PonyCui** [comment]
复用时，重新设置 videoItem，如果需要播放，重新调用 startAnimation。

**Comment by ansen666** [comment]
videoItem可以复用吗？RecyclerView的item里面的svga每次复用videoItem

**Comment by PonyCui** [comment]
可以，甚至可以跨多个 Player 复用。

**Comment by ansen666** [comment]
好的 谢谢了哈 我的问题解决了 非常感谢
