### ISSUE TITLE
能否提供HarmonyOS NEXT平台基于ArkUI的sdk？

### ISSUE THREAD

**Issue by robin8yeung** [svga/docs#52]
能否提供HarmonyOS NEXT平台基于ArkUI的sdk？

**Comment by xingyao1015** [comment]
同求支持HarmonyOS NEXT平台基于ArkUI的sdk

**Comment by actionbar** [comment]
https://ohpm.openharmony.cn/#/cn/detail/@tb-open%2Fsvga
